# Write your MySQL query statement below

WITH RANKED AS(
    SELECT 
    EMPLOYEE.ID , EMPLOYEE.SALARY,
    RANK() OVER(PARTITION BY EMPLOYEE.DEPARTMENTID ORDER BY EMPLOYEE.SALARY DESC) AS `RANK`
    FROM EMPLOYEE
)

SELECT DEPARTMENT.NAME AS DEPARTMENT , EMPLOYEE.NAME AS EMPLOYEE , EMPLOYEE.SALARY
FROM EMPLOYEE
LEFT JOIN RANKED 
ON RANKED.ID = EMPLOYEE.ID
LEFT JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID = DEPARTMENT.ID
WHERE RANKED.RANK = 1;