# Write your MySQL query statement below     AMOUNT IS NULL
SELECT VISITS.CUSTOMER_ID , COUNT(DISTINCT VISITS.VISIT_ID) AS COUNT_NO_TRANS
FROM VISITS
LEFT JOIN TRANSACTIONS ON VISITS.VISIT_ID = TRANSACTIONS.VISIT_ID
WHERE TRANSACTIONS.VISIT_ID IS NULL
GROUP BY CUSTOMER_ID;