# Write your MySQL query statement below
SELECT PRICES.PRODUCT_ID ,IFNULL(ROUND(SUM(UNITS * PRICE) / SUM(UNITS) , 2) , 0) AS AVERAGE_PRICE
FROM PRICES
LEFT JOIN UNITSSOLD
ON PRICES.PRODUCT_ID = UNITSSOLD.PRODUCT_ID
AND PRICES.START_DATE <= UNITSSOLD.PURCHASE_DATE
AND UNITSSOLD.PURCHASE_DATE <= PRICES.END_DATE
GROUP BY PRICES.PRODUCT_ID;

# Write your MySQL query statement below
-- SELECT 
--     p.PRODUCT_ID, 
--     ROUND(SUM(u.UNITS * p.PRICE) / SUM(u.UNITS) , 2) AS AVERAGE_PRICE
-- FROM PRICES p
-- JOIN UNITSSOLD u
--     ON p.PRODUCT_ID = u.PRODUCT_ID
--    AND u.PURCHASE_DATE BETWEEN p.START_DATE AND p.END_DATE
-- GROUP BY p.PRODUCT_ID;
