# Write your MySQL query statement below
WITH CTE AS(
    SELECT ID AS MANAGERID , SALARY AS MANAGERSALARY
    FROM EMPLOYEE
)
SELECT NAME AS EMPLOYEE
FROM EMPLOYEE
JOIN CTE 
ON  CTE.MANAGERID = EMPLOYEE.MANAGERID
WHERE EMPLOYEE.SALARY > CTE.MANAGERSALARY;